### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by abceater** [infoAppDev/OpenUIKit#2]
Hi, I am very interested in trying out your UI Kit, please can you let me know how to get started? Is this available on Nuget?

Is it possible to use aspects of the kit without including the entire library?

Thanks for the great work!

**Comment by rizaanlakay** [comment]
@abceater thank you for the positive feedback. I'm going to put together a how to guide shortly.

**Comment by rizaanlakay** [comment]
If you starting a new project, I would suggest just cloning the repo and then modifying the code, but if you want to add it to an existing project, I have updated the documentation on the home page of this project.

Enjoy.
